# Generated by Django 4.2.1 on 2023-07-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_itemimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='image',
            new_name='images',
        ),
    ]
