# Generated by Django 4.2.1 on 2023-07-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_itemimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
